// ─── Movie Data ────────────────────────────────────────────────────────────────
// Edit these arrays to add, remove, or change movies.
// Each movie needs: id, title, year, genre, rating, poster (URL), description

const DEFAULT_RECOMMENDATIONS = [
  {
    id: 1,
    title: "Inception",
    year: 2010,
    genre: "Sci-Fi",
    rating: 8.8,
    poster: "https://image.tmdb.org/t/p/w500/9gk7adHYeDvHkCSEqAvQNLV5Uge.jpg",
    description: "A thief who enters the dreams of others to steal secrets from their subconscious.",
  },
  {
    id: 2,
    title: "3 Idiots",
    year: 2009,
    genre: "Drama / Comedy",
    rating: 8.4,
    poster: "https://image.tmdb.org/t/p/w500/66A9MqXOyVFCssoloscw79z8Tew.jpg",
    description: "Two friends search for their long-lost companion while recounting their adventures at an engineering college.",
  },
  {
    id: 3,
    title: "The Dark Knight",
    year: 2008,
    genre: "Action",
    rating: 9.0,
    poster: "https://image.tmdb.org/t/p/w500/qJ2tW6WMUDux911r6m7haRef0WH.jpg",
    description: "Batman faces the Joker, a criminal mastermind who seeks to plunge Gotham into anarchy.",
  },
  {
    id: 4,
    title: "Dangal",
    year: 2016,
    genre: "Drama / Sports",
    rating: 8.3,
    poster: "https://image.tmdb.org/t/p/w500/1CoKNi3XVyijPCvy0usDbSWEXAg.jpg",
    description: "A former wrestler trains his daughters to become world-class female wrestlers.",
  },
  {
    id: 5,
    title: "Interstellar",
    year: 2014,
    genre: "Sci-Fi",
    rating: 8.6,
    poster: "https://image.tmdb.org/t/p/w500/gEU2QniE6E77NI6lCU6MxlNBvIx.jpg",
    description: "A team of explorers travel through a wormhole in space to ensure humanity's survival.",
  },
  {
    id: 6,
    title: "Andhadhun",
    year: 2018,
    genre: "Thriller",
    rating: 8.2,
    poster: "https://image.tmdb.org/t/p/w500/dy3K6hNvwE05siGgiLJcEiwgpdO.jpg",
    description: "A series of mysterious events change the life of a blind pianist who witnesses a murder.",
  },
  {
    id: 7,
    title: "Pulp Fiction",
    year: 1994,
    genre: "Crime",
    rating: 8.9,
    poster: "https://image.tmdb.org/t/p/w500/d5iIlFn5s0ImszYzBPb8JPIfbXD.jpg",
    description: "The lives of two hitmen, a boxer, and a pair of diner bandits intertwine in four tales of violence.",
  },
  {
    id: 8,
    title: "Taare Zameen Par",
    year: 2007,
    genre: "Drama",
    rating: 8.5,
    poster: "https://image.tmdb.org/t/p/w500/puHRt6Raovm5ujGCdwLWvRv4NHU.jpg",
    description: "An eight-year-old boy is thought to be lazy and troubled, until a new art teacher discovers that he has dyslexia.",
  },
];

const DEFAULT_HISTORY = [
  {
    id: 101,
    title: "Oppenheimer",
    year: 2023,
    genre: "Drama",
    rating: 8.4,
    poster: "https://image.tmdb.org/t/p/w500/8Gxv8gSFCU0XGDykEGv7zR1n2ua.jpg",
    description: "The story of J. Robert Oppenheimer and his role in the development of the atomic bomb.",
    watchedAt: "2024-03-20",
  },
  {
    id: 102,
    title: "Dil Chahta Hai",
    year: 2001,
    genre: "Comedy / Drama",
    rating: 8.1,
    poster: "https://image.tmdb.org/t/p/w500/c6Cicaf2FFmfcInfsbPTxMLk5CS.jpg",
    description: "Three inseparable childhood friends grow up and drift apart due to different life choices and loves.",
    watchedAt: "2024-03-10",
  },
  {
    id: 103,
    title: "The Matrix",
    year: 1999,
    genre: "Sci-Fi",
    rating: 8.7,
    poster: "https://image.tmdb.org/t/p/w500/f89U3ADr1oiB1s9GkdPOEpXUk5H.jpg",
    description: "A hacker discovers the true nature of reality and joins a rebellion against its controllers.",
    watchedAt: "2024-02-28",
  },
  {
    id: 104,
    title: "Zindagi Na Milegi Dobara",
    year: 2011,
    genre: "Drama / Adventure",
    rating: 8.1,
    poster: "https://image.tmdb.org/t/p/w500/hKO9O715wYxjkQSEv47giCYcyO8.jpg",
    description: "Three friends decide to turn their bachelor trip to Spain into a journey of self-discovery.",
    watchedAt: "2024-02-15",
  },
  {
    id: 105,
    title: "Parasite",
    year: 2019,
    genre: "Thriller",
    rating: 8.5,
    poster: "https://image.tmdb.org/t/p/w500/7IiTTgloJzvGI1TAYymCfbfl3vT.jpg",
    description: "A poor Korean family schemes to become employed by a wealthy family through deception.",
    watchedAt: "2024-01-30",
  },
  {
    id: 106,
    title: "Gully Boy",
    year: 2019,
    genre: "Drama / Music",
    rating: 7.9,
    poster: "https://image.tmdb.org/t/p/w500/4RE7TD5TqEXbPKyUHcn7CSeMlrJ.jpg",
    description: "A young man from the Mumbai slums chases his dream of becoming a rapper against all odds.",
    watchedAt: "2024-01-12",
  },
];

const DEFAULT_WATCHLIST = [
  {
    id: 201,
    title: "Sholay",
    year: 1975,
    genre: "Action / Drama",
    rating: 8.2,
    poster: "https://image.tmdb.org/t/p/w500/ya9bwgqA4eNl5bQ9QqS0jcmRoBS.jpg",
    description: "A retired police officer enlists the help of two criminals to capture a ruthless bandit.",
    addedAt: "2024-03-18",
  },
  {
    id: 202,
    title: "Whiplash",
    year: 2014,
    genre: "Drama / Music",
    rating: 8.5,
    poster: "https://image.tmdb.org/t/p/w500/7fn624j5lj3xTme2SgiLCeuedmO.jpg",
    description: "A promising young drummer enrolls at a cutthroat music conservatory under an abusive instructor.",
    addedAt: "2024-03-15",
  },
  {
    id: 203,
    title: "Dilwale Dulhania Le Jayenge",
    year: 1995,
    genre: "Romance / Drama",
    rating: 8.1,
    poster: "https://image.tmdb.org/t/p/w500/2CAL2433ZeIihfX1Hb2139CX0pW.jpg",
    description: "A young man and woman fall in love on a European trip, but her father has already arranged her marriage.",
    addedAt: "2024-03-10",
  },
  {
    id: 204,
    title: "Arrival",
    year: 2016,
    genre: "Sci-Fi",
    rating: 7.9,
    poster: "https://image.tmdb.org/t/p/w500/pEzNVQfdzYDzVK0XqxERIw2x2se.jpg",
    description: "A linguist works with the military to communicate with alien lifeforms after twelve mysterious spacecraft appear.",
    addedAt: "2024-03-05",
  },
  {
    id: 205,
    title: "PK",
    year: 2014,
    genre: "Comedy / Drama",
    rating: 8.1,
    poster: "https://image.tmdb.org/t/p/w500/z2x2Y4tncefsIU7h82gmUM5vnBJ.jpg",
    description: "An alien who comes to Earth on a research mission gets stranded and relies on the kindness of a young journalist.",
    addedAt: "2024-02-28",
  },
];
